#ifndef LAB_07_CONSTANTS_H
#define LAB_07_CONSTANTS_H

#define ERR_OK 0
#define ERR_FOURTH_FLAG 1
#define ERR_COUNT_ARGS 2
#define ERR_OPEN_SRC 3
#define ERR_END_LESS_START 4
#define ERR_NULL_POINTER 5
#define ERR_EMPTY_FILTER_ARRAY 6
#define ERR_PB_DST 7
#define ERR_READ_FROM_FILE_DURING_COUNT 8
#define ERR_READ_FROM_FILE 9
#define ERR_LESS_DATA 10
#define ERR_EMPTY_SRC_ARRAY 11
#define ERR_SRC_MEMORY 12
#define ERR_OPEN_DEST 13

#endif //LAB_07_CONSTANTS_H
