#ifndef LAB_08_CONSTANTS_H
#define LAB_08_CONSTANTS_H

#define ERR_OK 0
#define ERR_ARGS 1
#define ERR_ALLOCATE_MATRIX 2
#define ERR_ALLOCATE_ROW 3
#define ERR_READ_SIZE 4
#define ERR_WRONG_SIZE 5
#define ERR_READ_MATRIX 6
#define ERR_DIFFERENT_SIZE_FOR_ADDITION 7
#define ERR_WRONG_SIZE_FOR_MULTIPLICATION 8
#define ERR_OPEN_FIRST_FILE 9
#define ERR_OPEN_SECOND_FILE 10
#define ERR_OPEN_RES_FILE 11
#define ERR_NOT_SQUARE_MATRIX 12
#define ERR_DRAFT_ALLOC 13
#define ERR_NULL 14

#define TRUE 1
#define FALSE 0

#endif //LAB_08_CONSTANTS_H
